[features]
seeds = false
skip-lint = false
[programs.localnet]
ed25519_poc = "GTUsCbZ9e3doYtwcGpgZfSTpWtk2drV34kZNTb7MApcw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/imentus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
